### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted

### ISSUE THREAD

**Issue by q2apro** [jenstornell/tiny-html-minifier#20] opened 2018-06-25 18:13 UTC
Trying this HTML minifier on a live production. Sometimes it throws: 

```
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 81920 bytes) in tiny-html-minifier.php on line 33
```

How can we fix this? And is this happening because of false HTML markup (like unclosed tags)?

**Comment by jenstornell** [comment] 2018-08-19 05:47
So far this script does not care at all about open or closed tags. It just looks at `<` and `>` so that's not the problem.

I'm not sure what it is and because I can't reproduce the problem, it's hard to fix it.

**Comment by Flippo-xyz** [comment] 2018-10-10 21:20
I have the same issue. If you want a FTP access to reproduce it, lemme know.

**Comment by colethorsen** [comment] 2018-11-23 18:02
This should be fixed by the latest commit.

**Closed** 2018-11-23 18:03 UTC
